name: learning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  url_launcher: ^6.2.5
  lottie: ^2.7.0
  flutter_tts: ^4.2.3
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/unisza.png
    - assets/machine.png
    - assets/pressure.png
    - assets/FRIT.png
    - assets/POLY.png
    - assets/mesen.png
    - assets/animations/quiz.json
    - assets/Y.jpg
    - assets/q.png
    - assets/wall.jpg
    - assets/bs.png
    - assets/gb.png
    - assets/motor.png
    - assets/sc.png
    - assets/vacuum.png
    - assets/feeder.png
    - assets/wall1.jpg
    - assets/sounds/audio.mp3 
    - assets/sounds/yeay.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
