name: learning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  url_launcher: ^6.2.5
  lottie: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/unisza.png
    - assets/machine.png
    - assets/pressure.png
    - assets/video.mp4
    - assets/FRIT.png
    - assets/POLY.png
    - assets/mesen.png
    - assets/animations/quiz.json
    - assets/Y.jpg
    - assets/q.png
